In [35]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
# ! pip install imblearn

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head(20)

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N
5,25000.0,0.1797,634.43,MORTGAGE,90000.0,Source Verified,Mar-2019,low_risk,n,18.49,...,93.1,66.7,0.0,0.0,550717.0,418934.0,18800.0,369051.0,N,N
6,20400.0,0.2000,540.48,RENT,51315.0,Source Verified,Mar-2019,low_risk,n,25.63,...,100.0,0.0,1.0,0.0,40023.0,23469.0,3500.0,27523.0,N,N
7,10000.0,0.1557,349.46,OWN,66000.0,Source Verified,Mar-2019,low_risk,n,9.00,...,100.0,16.7,0.0,0.0,29300.0,22377.0,8400.0,12500.0,N,N
8,14000.0,0.0881,443.96,RENT,45000.0,Not Verified,Mar-2019,low_risk,n,10.24,...,100.0,0.0,0.0,0.0,25100.0,9724.0,12100.0,3000.0,N,N
9,10000.0,0.1474,345.39,RENT,63295.0,Verified,Mar-2019,low_risk,n,39.34,...,97.2,71.4,0.0,0.0,119822.0,102924.0,15300.0,80722.0,N,N
10,8500.0,0.0819,267.11,RENT,75000.0,Not Verified,Mar-2019,low_risk,n,17.31,...,100.0,0.0,0.0,0.0,75000.0,57756.0,18000.0,57000.0,N,N
11,10000.0,0.1171,330.76,RENT,54000.0,Not Verified,Mar-2019,low_risk,n,21.49,...,100.0,0.0,0.0,0.0,152500.0,42343.0,85000.0,65500.0,N,N
12,30000.0,0.1033,642.30,MORTGAGE,100000.0,Source Verified,Mar-2019,low_risk,n,8.00,...,100.0,0.0,0.0,0.0,50200.0,17323.0,29200.0,20000.0,N,N
13,15800.0,0.1640,387.60,MORTGAGE,62000.0,Source Verified,Mar-2019,low_risk,n,8.44,...,100.0,50.0,0.0,0.0,195700.0,18726.0,15900.0,4100.0,N,N
14,18000.0,0.1557,433.63,MORTGAGE,60000.0,Verified,Mar-2019,low_risk,n,62.80,...,100.0,25.0,0.0,0.0,196496.0,170509.0,10200.0,73796.0,N,N
15,40000.0,0.2250,1537.99,MORTGAGE,54000.0,Verified,Mar-2019,low_risk,n,59.09,...,100.0,100.0,0.0,0.0,123858.0,107194.0,19100.0,64858.0,N,N
16,14400.0,0.1390,491.46,RENT,100350.0,Source Verified,Mar-2019,low_risk,n,30.42,...,98.1,7.7,1.0,0.0,156028.0,104873.0,49000.0,88928.0,N,N
17,9600.0,0.0881,304.43,RENT,92000.0,Not Verified,Mar-2019,low_risk,n,20.01,...,76.2,100.0,0.0,0.0,58335.0,43218.0,6300.0,46535.0,N,N
18,16000.0,0.1719,399.28,MORTGAGE,72500.0,Source Verified,Mar-2019,low_risk,n,17.00,...,100.0,50.0,0.0,0.0,217738.0,52114.0,8500.0,49727.0,N,N
19,20000.0,0.0756,622.68,RENT,175000.0,Not Verified,Mar-2019,low_risk,n,11.28,...,93.8,75.0,0.0,0.0,84966.0,65106.0,20500.0,55785.0,N,N

In [9]:
# how would I filter to column to only get one kind of answer in it ?
late = df.loc[:,'loan_status'] == 'Late (31-120 days)'
print(type(late))
print(late)

<class 'pandas.core.series.Series'>
0        False
1        False
2        False
3        False
4        False
         ...
68812    False
68813    False
68814    False
68815    False
68816    False
Name: loan_status, Length: 68817, dtype: bool

In [26]:
# late1 = df.loc[:,'loan_status' == 'Late (31-120 days)' ] 
# i need to loop to get this to work late1
# didnt work 


late3 = [i for i in df.loc[:,'loan_status'] if i in 'low_risk']
len(late3)

68470

In [36]:


late4 = [i for i in df.loc[:,'loan_status'] if i not in ['Late (31-120 days)', 'Late (16-30 days)']]

In [6]:
y = df.loc[:,"loan_status"]
print(type(y))
print(y)

<class 'pandas.core.series.Series'>
0        low_risk
1        low_risk
2        low_risk
3        low_risk
4        low_risk
           ...
68812    low_risk
68813    low_risk
68814    low_risk
68815    low_risk
68816    low_risk
Name: loan_status, Length: 68817, dtype: object

# Split the Data into Training and Testing

In [7]:
# Create our features
 # YOUR CODE HEREd
# Define features set
X = df.copy()
X = X.drop(columns="loan_status")
X = pd.get_dummies(X)
# to make all catagorical columns in binary 
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [8]:
y.describe()

count        68817
unique           2
top       low_risk
freq         68470
Name: loan_status, dtype: object

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [ ]:
##both x and y are set above

In [33]:
# x.value_counts() ## NO value counts for dictionary

AttributeError: 'dict' object has no attribute 'value_counts'

In [18]:
# quotes for name of column 
# # here we created variable then calling variable - no quotes 
# y = df[[target]]

In [10]:
# Check the balance of our target values
y.value_counts()
# other wise if you want y["loan_status"].value_counts() need to make df 
# of one column then call value counts

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [11]:
# Split the X and y into X_train, X_test, y_train, y_test
# YOUR CODE HERE
# Splitting into Train and Test sets.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
# Resample the training data with the RandomOversampler
from imblearn.ensemble import BalancedRandomForestClassifier
br_fc = BalancedRandomForestClassifier(n_estimators=128, random_state=1)
br_fc.fit(X_train,y_train)

BalancedRandomForestClassifier(n_estimators=128, random_state=1)

In [13]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

predictions = br_fc.predict(X_test)
acc_score=balanced_accuracy_score(y_test,predictions)

In [14]:
acc_score = balanced_accuracy_score(y_test,predictions)
acc_score

0.7825242188115316

In [15]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           62           30
Actual 1         1863        15250

In [17]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import classification_report
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           62           30
Actual 1         1863        15250

Accuracy Score : 0.7825242188115316
Classification Report
              precision    recall  f1-score   support

   high_risk       0.03      0.67      0.06        92
    low_risk       1.00      0.89      0.94     17113

    accuracy                           0.89     17205
   macro avg       0.52      0.78      0.50     17205
weighted avg       0.99      0.89      0.94     17205

In [18]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test,predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.67      0.89      0.06      0.77      0.59        92
   low_risk       1.00      0.89      0.67      0.94      0.77      0.61     17113

avg / total       0.99      0.89      0.68      0.94      0.77      0.61     17205

In [13]:
#mine is above , the one from the template is below 
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.67      0.90      0.07      0.78      0.59       101
   low_risk       1.00      0.90      0.67      0.95      0.78      0.62     17104

avg / total       0.99      0.90      0.67      0.94      0.78      0.62     17205

In [19]:
print(X.columns)

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'issue_d_Feb-2019', 'issue_d_Jan-2019', 'issue_d_Mar-2019',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'next_pymnt_d_Apr-2019', 'next_pymnt_d_May-2019',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'debt_settlement_flag_N'],
      dtype='object')

In [21]:
importances = br_fc.feature_importances_
importances

## need to loop through x to connect to variable 
# print(X.columns) 
for i in range(len(X.columns)):
    print(f"{X.columns.values[i]}, {importances[i]}")
     
    # connect columns heading in X to percentages in importances
    # need list of column heddings

loan_amnt, 0.012822985523831121
int_rate, 0.030112430045584074
installment, 0.013830563268789012
annual_inc, 0.013737835127619448
dti, 0.018246145738451226
delinq_2yrs, 0.004585875278797847
inq_last_6mths, 0.009157407119417697
open_acc, 0.010127645234302082
pub_rec, 0.0012279231052273237
revol_bal, 0.01482371229303645
total_acc, 0.011087331860431966
out_prncp, 0.013204399874630663
out_prncp_inv, 0.013366975442553006
total_pymnt, 0.05761167564095468
total_pymnt_inv, 0.07245075778590966
total_rec_prncp, 0.07927165931443968
total_rec_int, 0.05197118846698988
total_rec_late_fee, 0.008013914057766428
recoveries, 0.0
collection_recovery_fee, 0.0
last_pymnt_amnt, 0.054799508813328075
collections_12_mths_ex_med, 0.00039419081932608445
policy_code, 0.0
acc_now_delinq, 0.0
tot_coll_amt, 0.0025938502185704248
tot_cur_bal, 0.012547604509801103
open_acc_6m, 0.0042758990910203515
open_act_il, 0.0058357198491219755
open_il_12m, 0.0032051669411261212
open_il_24m, 0.006521798772198221
mths_since_rcnt_il, 0.013549137068364414
total_bal_il, 0.013491837514613076
il_util, 0.012059744606354826
open_rv_12m, 0.0044401479474661335
open_rv_24m, 0.006665522988131238
max_bal_bc, 0.014685109168851702
all_util, 0.011883090049122707
total_rev_hi_lim, 0.01427107035478609
inq_fi, 0.006605863202439448
total_cu_tl, 0.007157857372580206
inq_last_12m, 0.008850165665941588
acc_open_past_24mths, 0.008545595175763929
avg_cur_bal, 0.014441918548333146
bc_open_to_buy, 0.012950733860145135
bc_util, 0.013913377890288667
chargeoff_within_12_mths, 5.507984019502364e-05
delinq_amnt, 0.0
mo_sin_old_il_acct, 0.012973138217767008
mo_sin_old_rev_tl_op, 0.01991894059463552
mo_sin_rcnt_rev_tl_op, 0.010669247891794601
mo_sin_rcnt_tl, 0.008575045972122318
mort_acc, 0.006048703602187043
mths_since_recent_bc, 0.01118385051584502
mths_since_recent_inq, 0.014511819241652676
num_accts_ever_120_pd, 0.0027701743957837563
num_actv_bc_tl, 0.006079936328792666
num_actv_rev_tl, 0.008940183074611783
num_bc_sats, 0.009013270490633931
num_bc_tl, 0.008828509271571035
num_il_tl, 0.01104858659537128
num_op_rev_tl, 0.008982143195403637
num_rev_accts, 0.010503443573628094
num_rev_tl_bal_gt_0, 0.009148366536663689
num_sats, 0.010602515391602362
num_tl_120dpd_2m, 0.0
num_tl_30dpd, 0.0
num_tl_90g_dpd_24m, 0.0012684224934000922
num_tl_op_past_12m, 0.006776162920272113
pct_tl_nvr_dlq, 0.007316420223249569
percent_bc_gt_75, 0.007089886328559787
pub_rec_bankruptcies, 0.0008931259499349235
tax_liens, 0.0
tot_hi_cred_lim, 0.014271997581140311
total_bal_ex_mort, 0.01131859738855656
total_bc_limit, 0.01282268300677242
total_il_high_credit_limit, 0.012130027832866227
home_ownership_ANY, 0.000159796553260227
home_ownership_MORTGAGE, 0.0014104802328527082
home_ownership_OWN, 0.0020728746376759096
home_ownership_RENT, 0.0019098069886618165
verification_status_Not Verified, 0.0030111276851334154
verification_status_Source Verified, 0.0021214621538901746
verification_status_Verified, 0.0019103577525377729
issue_d_Feb-2019, 0.005046081050911024
issue_d_Jan-2019, 0.02638139427122888
issue_d_Mar-2019, 0.009576646006299469
pymnt_plan_n, 0.0
initial_list_status_f, 0.0013302578447145464
initial_list_status_w, 0.0015380797686958194
next_pymnt_d_Apr-2019, 0.003187249591780569
next_pymnt_d_May-2019, 0.004486559042896118
application_type_Individual, 0.0009285493002814578
application_type_Joint App, 0.0018536630577599062
hardship_flag_N, 0.0
debt_settlement_flag_N, 0.0

In [22]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE

importances = br_fc.feature_importances_
importances

array([1.28229855e-02, 3.01124300e-02, 1.38305633e-02, 1.37378351e-02,
       1.82461457e-02, 4.58587528e-03, 9.15740712e-03, 1.01276452e-02,
       1.22792311e-03, 1.48237123e-02, 1.10873319e-02, 1.32043999e-02,
       1.33669754e-02, 5.76116756e-02, 7.24507578e-02, 7.92716593e-02,
       5.19711885e-02, 8.01391406e-03, 0.00000000e+00, 0.00000000e+00,
       5.47995088e-02, 3.94190819e-04, 0.00000000e+00, 0.00000000e+00,
       2.59385022e-03, 1.25476045e-02, 4.27589909e-03, 5.83571985e-03,
       3.20516694e-03, 6.52179877e-03, 1.35491371e-02, 1.34918375e-02,
       1.20597446e-02, 4.44014795e-03, 6.66552299e-03, 1.46851092e-02,
       1.18830900e-02, 1.42710704e-02, 6.60586320e-03, 7.15785737e-03,
       8.85016567e-03, 8.54559518e-03, 1.44419185e-02, 1.29507339e-02,
       1.39133779e-02, 5.50798402e-05, 0.00000000e+00, 1.29731382e-02,
       1.99189406e-02, 1.06692479e-02, 8.57504597e-03, 6.04870360e-03,
       1.11838505e-02, 1.45118192e-02, 2.77017440e-03, 6.07993633e-03,
       8.94018307e-03, 9.01327049e-03, 8.82850927e-03, 1.10485866e-02,
       8.98214320e-03, 1.05034436e-02, 9.14836654e-03, 1.06025154e-02,
       0.00000000e+00, 0.00000000e+00, 1.26842249e-03, 6.77616292e-03,
       7.31642022e-03, 7.08988633e-03, 8.93125950e-04, 0.00000000e+00,
       1.42719976e-02, 1.13185974e-02, 1.28226830e-02, 1.21300278e-02,
       1.59796553e-04, 1.41048023e-03, 2.07287464e-03, 1.90980699e-03,
       3.01112769e-03, 2.12146215e-03, 1.91035775e-03, 5.04608105e-03,
       2.63813943e-02, 9.57664601e-03, 0.00000000e+00, 1.33025784e-03,
       1.53807977e-03, 3.18724959e-03, 4.48655904e-03, 9.28549300e-04,
       1.85366306e-03, 0.00000000e+00, 0.00000000e+00])

### Easy Ensemble AdaBoost Classifier

In [15]:
# Train the Classifier
# YOUR CODE HERE

EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=1,
            random_state=1, replacement=False, sampling_strategy='auto',
            verbose=0, warm_start=False)

In [29]:
from imblearn.ensemble import EasyEnsembleClassifier
ada_boost = EasyEnsembleClassifier(n_estimators=128, random_state=1)
ada_boost.fit(X_train,y_train)

EasyEnsembleClassifier(n_estimators=128, random_state=1)

In [30]:
ada_predictions = ada_boost.predict(X_test)
# create predictions of what the y could be using the easy ensemble classifier on the 
# x testing data

In [31]:
ada_acc_score=balanced_accuracy_score(y_test,ada_predictions)
ada_acc_score

0.9303431284124197

In [16]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

0.9316600714093861

In [32]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, ada_predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           85            7
Actual 1         1082        16031

In [33]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import classification_report
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, adapredictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           85            7
Actual 1         1082        16031

Accuracy Score : 0.9303431284124197
Classification Report
              precision    recall  f1-score   support

   high_risk       0.07      0.92      0.14        92
    low_risk       1.00      0.94      0.97     17113

    accuracy                           0.94     17205
   macro avg       0.54      0.93      0.55     17205
weighted avg       0.99      0.94      0.96     17205

There is a increase in precission, recall and thus f1when using the adaboost classifier called "EasyEnsembleClassifier" when compared to the the balanced random forrest classifier. 
for high risk loans the precission went up from .03 to .07 the recall went from .67 to .92 which is the largerst increase in all of the factors shown. 
the f1 went up from .06 using the random forest to .14 when using the adaboost method.

In [17]:
# Display the confusion matrix
# YOUR CODE HERE

array([[   93,     8],
       [  983, 16121]])

In [34]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test,ada_predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.07      0.92      0.94      0.14      0.93      0.86        92
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17113

avg / total       0.99      0.94      0.92      0.96      0.93      0.87     17205

In [18]:
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205